<?php

namespace AppBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends AbstractRepository
{
    public function search($customerId, $order = 'asc', $limit = 20, $offset = 0)
    {
        $query = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->innerJoin('a.user', 'u')
            ->addSelect('u')
            ->where('u.customer = :customer_id')
            ->setParameter('customer_id', $customerId)
            ->orderBy('u.username', $order);

        return $this->paginate($query, $limit, $offset);
    }
}
