<?php

namespace AppBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends AbstractRepository
{
    /**
     * @param string $order
     * @param int $limit
     * @param int $offset
     * @return \Pagerfanta\Pagerfanta
     */
    public function search($order = 'asc', $limit = 20, $offset = 0)
    {
        $query = $this
            ->createQueryBuilder('b')
            ->select('b')
            ->orderBy('b.name', $order);

        return $this->paginate($query, $limit, $offset);
    }
}

