<?php

namespace AppBundle\Repository;

/**
 * MobilePhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobilePhoneRepository extends AbstractRepository
{
    public function search($brand, $order = 'asc', $limit = 20, $offset = 1)
    {
        $qb = $this
            ->createQueryBuilder('mp')
            ->select('mp')
            ->orderBy('mp.model', $order)
        ;

        if ($brand) {
            $qb
                ->where('mp.brand = :brand')
                ->setParameter('brand', $brand)
            ;
        }

        return $this->paginate($qb, $limit, $offset);
    }
}
