<?php

namespace AppBundle\Repository;

/**
 * MobilePhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobilePhoneRepository extends AbstractRepository
{
    public function search($term, $order = 'asc', $limit = 20, $offset = 0)
    {
        $query = $this
            ->createQueryBuilder('mp')
            ->select('mp')
            ->orderBy('mp.model', $order)
        ;
        if ($term) {
            $query = $query
                ->where('mp.model LIKE ?1')
                ->setParameter(1, '%'.$term.'%')
            ;
        }

        return $this->paginate($query, $limit, $offset);
    }
}
