<?php

namespace AppBundle\Repository;

/**
 * OsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsRepository extends \Doctrine\ORM\EntityRepository
{
}
