<?php

namespace AppBundle\Repository;

/**
 * OsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsRepository extends AbstractRepository
{
    /**
     * @param string $order
     * @param int $limit
     * @param int $offset
     * @return \Pagerfanta\Pagerfanta
     */
    public function search($order = 'asc', $limit = 20, $offset = 0)
    {
        $query = $this
            ->createQueryBuilder('o')
            ->select('o')
            ->orderBy('o.name', $order);

        return $this->paginate($query, $limit, $offset);
    }
}
