<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractRepository
{
    public function search($customerId, $term, $order = 'asc', $limit = 20, $offset = 0)
    {
        $query = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->where('u.customer = :customer_id')
            ->setParameter('customer_id', $customerId)
            ->orderBy('u.username', $order)
        ;
        if ($term) {
            $query = $query
                ->where('u.username LIKE ?1')
                ->setParameter(1, '%'.$term.'%')
            ;
        }

        return $this->paginate($query, $limit, $offset);
    }
}
