imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
         engines: ['twig', 'php']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    param_fetcher_listener: force
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
           { AppBundle\Exception\ResourceValidationException: 400, AppBundle\Exception\ResourceNotFoundException: 404, AppBundle\Exception\ResourceAccessForbiddenException: 403,\Exception: 500 }
        messages:
           { AppBundle\Exception\ResourceValidationException: true, AppBundle\Exception\ResourceNotFoundException: true, AppBundle\Exception\ResourceAccessForbiddenException: true }
    versioning:
        enabled: true
        resolvers:
            #query: true # Query parameter: /users?version=v1
            #custom_header: true # X-Accept-Version header
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'

sensio_framework_extra:
#   view: { annotations: false }
    request: { converters: true }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\Customer
    from_email:
        address: contact@bilemo.com
        sender_name: bilemo

fos_oauth_server:
    db_driver: orm       # Drivers available: orm, mongodb, or propel
    client_class:        AppBundle\Entity\Client
    access_token_class:  AppBundle\Entity\AccessToken
    refresh_token_class: AppBundle\Entity\RefreshToken
    auth_code_class:     AppBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username
        options:
            access_token_lifetime: 3600
            token_type: Bearer
            supported_scopes: customer

nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
    documentation:
        info:
            title: BileMo API Documentation
            description: |
                API for Bilemo's Mobile Phones and users of BileMo's customers.

                To access to the resources you must be authenticated with an access token.
            version: 1.0.0
        definitions:
            Authentication:
              type: object
              properties:
                grant_type:
                  type: string
                client_id:
                  type: string
                client_secret:
                  type: string
                username:
                  type: string
                password:
                  type: string
            AccessToken:
              type: object
              properties:
                access_token:
                  type: string
                expires_in:
                  type: integer
                token_type:
                  type: string
                scope:
                  type: string
                refresh_token:
                  type: string
            GetAddressByID:
              type: object
              properties:
                recipient:
                  type: string
                street_address:
                  type: string
                  format: maxLenght 255
                zip_code:
                  type: string
                  format: maxLenght 5
                city:
                  type: string
                  format: maxLenght 255
                country:
                  type: string
                  format: maxLenght 255
                is_active:
                  type: boolean
                _embedded:
                  type: object
                  properties:
                    user:
                      type: object
                      properties:
                        username:
                          type: string
              required:
                - recipient
                - city
                - country
            GetBrandByID:
              type: object
              properties:
                name:
                  type: string
                  format: maxLenght 255
                _embedded:
                  type: object
                  properties:
                    mobilephones:
                      type: object
                      properties:
                        model:
                          type: string
              required:
                - name
            GetImageByID:
              type: object
              properties:
                extension:
                  type: string
                  format: maxLenght 45
                alt:
                  type: string
                  format: maxLenght 255
                _embedded:
                  type: object
                  properties:
                    mobilephones:
                      type: object
                      properties:
                        model:
                          type: string
              required:
                - extension
                - alt
            GetMobilePhoneByID:
              type: object
              properties:
                model:
                  type: string
                  format: maxLenght 255
                reference:
                  type: string
                  format: maxLenght 255
                capacity_gb:
                  type: integer
                display_inch:
                  type: number
                  format: float
                camera_mp:
                  type: integer
                color:
                  type: string
                  format: maxLenght 255
                description:
                  type: string
                height_mm:
                  type: number
                  format: float
                width_mm:
                  type: number
                  format: float
                depth_mm:
                  type: number
                  format: float
                weight_grams:
                  type: integer
                price_euros:
                  type: integer
                price_cents:
                  type: integer
                _embedded:
                  type: object
                  properties:
                    brands:
                      type: object
                      properties:
                        name:
                          type: string
                    os:
                      type: object
                      properties:
                        name:
                          type: string
                    images:
                      type: object
                      properties:
                        extension:
                          type: string
                        alt:
                          type: string
              required:
                - model
                - reference
                - color
                - description
            GetOsByID:
              type: object
              properties:
                name:
                  type: string
                  format: maxLenght 255
                _embedded:
                  type: object
                  properties:
                    mobilephones:
                      type: object
                      properties:
                        model:
                          type: string
              required:
                - name
            PostAddress:
              type: object
              properties:
                recipient:
                  type: string
                street_address:
                  type: string
                  format: maxLenght 255
                zip_code:
                  type: string
                  format: maxLenght 5
                city:
                  type: string
                  format: maxLenght 255
                country:
                  type: string
                  format: maxLenght 255
              required:
                - recipient
                - city
                - country
            PostUser:
              type: object
              properties:
                username:
                  type: string
                  format: maxLenght 255
                first_name:
                  type: string
                  format: maxLenght 255
                last_name:
                  type: string
                  format: maxLenght 255
                email:
                  type: string
                  format: maxLenght 255, email
                plain_password:
                  type: string
                addresses:
                  type: array
                  items:
                    $ref: "#/definitions/PostAddress"
              required:
                - username
                - email
            GetUserByID:
              type: object
              properties:
                username:
                  type: string
                  format: maxLenght 255
                first_name:
                  type: string
                  format: maxLenght 255
                last_name:
                  type: string
                  format: maxLenght 255
                email:
                  type: string
                  format: maxLenght 255, email
                is_active:
                  type: boolean
                _embedded:
                  type: object
                  properties:
                    addresses:
                      type: object
                      properties:
                        recipient:
                          type: string
                        street_address:
                          type: string
                          format: maxLenght 255
                        zip_code:
                          type: string
                          format: maxLenght 5
                        city:
                          type: string
                          format: maxLenght 255
                        country:
                          type: string
                          format: maxLenght 255
                        is_active:
                          type: boolean
              required:
                - username
                - email
        paths:
            '/oauth/v2/token':
                post:
                    tags:
                        - Authentication
                    summary: Get your access token.
                    description: |
                        To get your access token, use your username, client public id and secret :
                        {
                          "grant_type": "password",
                          "client_id": "YourClientPublicId",
                          "client_secret": "YourClientSecret",
                          "username": "YourUsername",
                          "password": "YourPassword"
                        }
                    responses:
                        '200':
                            description: Successful request. Get access token.
                            schema:
                                $ref: "#/definitions/AccessToken"
                        '400':
                            description: Bad request.
                consumes:
                    - application/json
                parameters:
                    - in: "body"
                      name: "body"
                      description: "Parameters to get your access token."
                      required: true
                      schema:
                          $ref: "#/definitions/Authentication"
